language: java
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.m2"

env:
  - PROFILE=cdi
  - PROFILE=javaee
  - PROFILE=osgi,osgi-native
  - PROFILE=osgi,osgi-forked

stages:
  - build
  - test

install: true

script: mvn -U -Pitest -P${PROFILE} clean verify


jobs:
  include:
    - stage: build
      before_install:
      - openssl aes-256-cbc -K $encrypted_3146aa8efbe7_key -iv $encrypted_3146aa8efbe7_iv
        -in .maven-settings.xml.enc -out .maven-settings.xml -d
      install: true      
      script: mvn -s .maven-settings.xml -B clean deploy

